### ISSUE TITLE
Linear Stability for a Bickley jet

### ISSUE THREAD

**Issue by francispoulin** [pyqg/BAMS#1]
I wrote something up a while ago to compute the linear stability of a Bickley jet in a one-layer QG.  Sadly, I never figured out how to include it.  If there is interest in including this I can try and do this at some point.  

I think this would generalize quite easily to N-layers, but would be more expensive with each layer.

**Comment by cesar-rocha** [comment]
@francispoulin sure, but I we should pick this up in [pyqg](https://github.com/pyqg/pyqg). 

I started this repo for us to start drafting the BAMS paper to discuss what we want to say and  what remains to be done.
